title: "Tanishka Shah"
email: tanishkashah24@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi! I'm Tanishka Shah, an International Sophmore Studennt studying Interdisciplinary Computing with Biology at the University of Kansas.
baseurl: "/" 
url: "/Tani-Shah.github.io" 
twitter_username: Tani-Shah
github_username:  Tani-Shah

sass:
  sass_dir: _sass

#icon: ./assets/img/icon.jpg
