name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  PHP:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivmathur/setup-php@v2
        with:
          php-versions: '8.2'
          tools: laravel/pint

      - name: Check for syntax errors
        uses: overtrue/phplint@8.2
        with:
          path: '*'
          options: --exclude-vendor

      - name: Check for code style
        run: pint --test

